import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={cn("min-h-screen antialiased", inter.className)}>
        {children}
      </body>
      {/* eslint-disable-next-line @next/next/no-before-interactive-script-outside-document */}
      {/* <Script
        src="https://player.twitch.tv/js/embed/v1.js"
        strategy="beforeInteractive"
      /> */}
    </html>
  );
}
